/** business 层：产品域模块 */
export const businessEntries = {
  index: 'src/index.ts',
  'business/index': 'src/business/index.ts',
  'business/mmd/index': 'src/business/mmd/index.ts',
  'business/mmd/admin/index': 'src/business/mmd/admin/index.ts',
  'business/mmd/server/index': 'src/business/mmd/server/index.ts',
  'business/audioDetection/index': 'src/business/audioDetection/index.ts',
  'business/testYourself/index': 'src/business/testYourself/index.ts',
  'business/testYourself/admin/index': 'src/business/testYourself/admin/index.ts',
  'business/testYourself/server/index': 'src/business/testYourself/server/index.ts',
  'business/music/index': 'src/business/music/index.ts',
  'business/music/server/index': 'src/business/music/server/index.ts',
  'business/mikuFusionGame/index': 'src/business/mikuFusionGame/index.ts',
  'business/mikuFireworks3D/index': 'src/business/mikuFireworks3D/index.ts',
  'business/navigation/index': 'src/business/navigation/index.ts',
  'business/portfolio/index': 'src/business/portfolio/index.ts',
  'business/qqbot/server/index': 'src/business/qqbot/server/index.ts',
  'business/qqbot/ui/web/index': 'src/business/qqbot/ui/web/index.ts',
  'business/screenReceiver/index': 'src/business/screenReceiver/index.ts',
  'business/festivalCard/index': 'src/business/festivalCard/index.ts',
  'business/festivalCard/routes/index': 'src/business/festivalCard/routes/index.ts',
  'business/festivalCard/server/index': 'src/business/festivalCard/server/index.ts',
  'business/vocaloidBooth/index': 'src/business/vocaloidBooth/index.ts',
  'business/vocaloidBooth/web/index': 'src/business/vocaloidBooth/web/index.ts',
  'business/vocaloidBooth/server/index': 'src/business/vocaloidBooth/server/index.ts',
  'business/mikuContest/ui/web/index': 'src/business/mikuContest/ui/web/index.ts',
} as const satisfies Record<string, string>;
