/** @deprecated 请改引 `sa2kit/business/teachHub/domain` */
export type * from 'sa2kit/business/teachHub/domain';
export {
  TeachHubApiClient,
  type TeachHubApiConfig,
  type ApiEnvelope,
  TEACH_HUB_API_PREFIX,
  WORKSPACE_TABS,
  lessonTitleFromSlug,
  lessonFilenameFromSlug,
  type TeachHubScreen,
  type WorkspaceTabId,
  parseMissionMarkdown,
  extractMissionWhySummary,
  parseLearningRecordMarkdown,
  parseLearningRecordPath,
  recordSummary,
  composeLearningRecordMarkdown,
  listReferenceSlugs,
  fetchLearningRecords,
  parseResourcesMarkdown,
  composeResourcesMarkdown,
  DEFAULT_RESOURCES_MD,
  RESOURCE_CATEGORY_LABELS,
  RESOURCE_CATEGORY_DESCRIPTIONS,
  lessonProgressMap,
  mergeLessonsWithProgress,
  lessonProgressLabel,
  completedLessonCount,
  DEFAULT_MISSION_TEMPLATE,
  composeMissionMarkdown,
  isMissionReady,
  resolveGenerateLessonTrigger,
  generateLessonButtonLabel,
} from 'sa2kit/business/teachHub/domain';
