/**
 * sa2kit UI 门面：再导出 @sa2kit-ui/react（设计系统唯一实现源）。
 * 宿主与 business 应从此入口取组件 / ThemeProvider，勿直连 @sa2kit-ui/*（特殊情况须登记债）。
 *
 * 样式：`import 'sa2kit/common/ui/style'` 或 `@import 'sa2kit/common/ui/style'`
 *
 * 注意：必须显式 named re-export。`export *` 在 Next/webpack 经 CJS 互操作时
 * 会丢命名导出（Attempted import error: 'Button' is not exported）。
 */
export {
  Button,
  Input,
  Switch,
  Card,
  Typewriter,
  Modal,
  Title,
  Tabs,
  Collapse,
  Checkbox,
  Radio,
  Tooltip,
  Select,
  Loading,
  Divider,
  Time,
  CodeBlock,
  Table,
  Icon,
  ICON_LIST,
  ITEM_COUNT,
  ITEM_LIST,
  ITEM_URL_MAP,
  Footer,
  Phone,
  Cursor,
  Wallet,
  WeddingInvitation,
  WeddingInvitationExportButton,
  ThemeProvider,
  useTheme,
  SA2_THEMES,
} from '@sa2kit-ui/react';

export type {
  ButtonProps,
  ButtonType,
  ButtonSize,
  ButtonHTMLType,
  InputProps,
  InputSize,
  SwitchProps,
  SwitchSize,
  CardProps,
  CardType,
  CardColor,
  ModalProps,
  TitleProps,
  TitleSize,
  TitleColor,
  TabsProps,
  TabItem,
  CollapseProps,
  CheckboxProps,
  CheckboxOption,
  CheckboxSize,
  RadioProps,
  RadioOption,
  RadioSize,
  TypewriterProps,
  TooltipProps,
  TooltipPlacement,
  TooltipTrigger,
  TooltipVariant,
  SelectProps,
  SelectOption,
  LoadingProps,
  DividerProps,
  DividerType,
  TimeProps,
  CodeBlockProps,
  TableProps,
  TableColumn,
  IconProps,
  IconName,
  FooterProps,
  FooterType,
  PhoneProps,
  CursorProps,
  WalletProps,
  WalletSize,
  WeddingInvitationProps,
  WeddingInvitationRef,
  WeddingInvitationExportButtonProps,
  Sa2ThemeId,
  ThemeContextValue,
  ThemeProviderProps,
} from '@sa2kit-ui/react';
