import type { FestivalCardConfig } from '../types';

export const DEFAULT_FESTIVAL_CARD_CONFIG: FestivalCardConfig = {
  id: 'default-festival-card',
  name: 'Holiday Card',
  theme: 'winter',
  coverTitle: 'Happy Holidays',
  coverSubtitle: 'Warm wishes for you',
  background: {
    colorA: '#0c1a34',
    colorB: '#1f4f8a',
  },
  backgroundMusic: {
    src: '',
    loop: true,
    autoPlay: false,
    volume: 0.5,
  },
  pages: [
    {
      id: 'page-1',
      title: '封面',
      background: { color: '#11284d' },
      elements: [
        {
          id: 'p1-text-1',
          type: 'text',
          x: 50,
          y: 20,
          content: '新年快乐',
          fontSize: 34,
          fontWeight: 700,
          align: 'center',
          color: '#f8fafc',
        },
        {
          id: 'p1-text-2',
          type: 'text',
          x: 50,
          y: 36,
          content: '愿这一年平安喜乐',
          fontSize: 18,
          fontWeight: 500,
          align: 'center',
          color: '#dbeafe',
        },
        {
          id: 'p1-image-1',
          type: 'image',
          x: 50,
          y: 68,
          width: 72,
          height: 42,
          src: 'https://images.unsplash.com/photo-1512389142860-9c449e58a543?auto=format&fit=crop&w=1200&q=80',
          fit: 'cover',
          borderRadius: 16,
          alt: 'holiday',
        },
      ],
    },
    {
      id: 'page-2',
      title: '祝福',
      background: { color: '#1a3766' },
      elements: [
        {
          id: 'p2-text-1',
          type: 'text',
          x: 50,
          y: 28,
          content: '愿你新岁：',
          fontSize: 28,
          fontWeight: 700,
          align: 'center',
          color: '#fef3c7',
        },
        {
          id: 'p2-text-2',
          type: 'text',
          x: 50,
          y: 42,
          content: '所得皆所期，所失亦无碍',
          fontSize: 18,
          fontWeight: 500,
          align: 'center',
          color: '#f8fafc',
        },
        {
          id: 'p2-text-3',
          type: 'text',
          x: 50,
          y: 55,
          content: '愿你的每一步都走向光亮',
          fontSize: 16,
          fontWeight: 400,
          align: 'center',
          color: '#dbeafe',
        },
      ],
    },
    {
      id: 'page-3',
      title: '落款',
      background: { color: '#11284d' },
      elements: [
        {
          id: 'p3-image-1',
          type: 'image',
          x: 50,
          y: 34,
          width: 60,
          height: 42,
          src: 'https://images.unsplash.com/photo-1456324504439-367cee3b3c32?auto=format&fit=crop&w=1200&q=80',
          fit: 'cover',
          borderRadius: 14,
          alt: 'gift',
        },
        {
          id: 'p3-text-1',
          type: 'text',
          x: 50,
          y: 72,
          content: 'Best wishes, from SA2Kit',
          fontSize: 18,
          fontWeight: 600,
          align: 'center',
          color: '#f8fafc',
        },
      ],
    },
  ],
};
